name: CI/CD Pipeline

on:

  push:

    branches:

      - main

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v4

      - name: Login Docker

        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Image

        run: docker build -t ${{ secrets.DOCKER_USER }}/todo-app .

      - name: Push Image

        run: docker push ${{ secrets.DOCKER_USER }}/todo-app

      - name: Deploy to EC2

        uses: appleboy/ssh-action@v1.0.0

        with:

          host: ${{ secrets.EC2_HOST }}

          username: ${{ secrets.EC2_USER }}

          key: ${{ secrets.EC2_KEY }}

          script: |

            sudo docker pull ${{ secrets.DOCKER_USER }}/todo-app

            sudo docker stop todo || true

            sudo docker rm todo || true

            sudo docker run -d -p 3000:3000 --name todo ${{ secrets.DOCKER_USER }}/todo-app
 
 

 
